//import React from "react"

const MenuItems = [
    {key:18, url: '/proyectos',    caption: 'Proyectos',     icon: 'workflow'},
    {key:31, url: '/acciones',     caption: 'Acción',        icon: 'star'},
    //{key:28, url: '/accionestipo', caption: 'AccionesTipo'},
    //{key:29, url: '/accionestipoformacion', caption: 'AccionesTipoFormacion'},
    {key:19, url: '/participantes',caption: 'Participantes', icon: 'users'},
    {key:33, url: '/docentes',     caption: 'Docentes',      icon: 'user-plus'},
    {key:23, url: '/empresas',     caption: 'Empresas',      icon: 'briefcase'},
    {key:24, url: '/ofertas',      caption: 'Ofertas',       icon: 'coin'},
    //{key: 1, url: '/tittipo',      caption: 'Titulaciones Tipo'},
    //{key: 2, url: '/titnivel',     caption: 'Titulaciones Nivel'},
    //{key: 3, url: '/titulacionesf',caption: 'Titulaciones Familias'},
    {key: 4, url: '/titulaciones', caption: 'Titulaciones',  icon: 'books'},
    //{key:22, url: '/tipocontrato', caption: 'TipoContrato' },
    {key: 5, url: '/colectivos',   caption: 'Colectivos', icon: 'users'},
    //{key: 6, url: '/provincias',   caption: 'Provincias'},
    //{key:20, url: '/localidades',  caption: 'Municipios' },
    //{key:21, url: '/tiposvia',     caption: 'Tipos Via'},
    //{key: 7, url: '/cnaes',        caption: 'Cnae\'s'},
    //{key: 8, url: '/cnos',         caption: 'Cno\'s'},
    //{key: 9, url: '/experiencias', caption: 'Experiencia'},
    //{key:10, url: '/salarios',     caption: 'Rangos Sal.'},
    //{key:11, url: '/mbaja',        caption: 'Mot. Baja'},
    //{key:12, url: '/horarios',     caption: 'Horarios'},
    {key:13, url: '/dgeografica',  caption: 'Geográficas', icon: 'geolocation'},
    {key:37, url: '/lugares',      caption: 'Lugares'},
    {key:14, url: '/cofinanciadas',caption: 'Cofinanciadas'},
    {key:15, url: '/tecnicos',     caption: 'Tecnicos'},
    {key:16, url: '/convocatorias',caption: 'Convocatorias'},
    {key:17, url: '/ambitos' ,     caption: 'Ámbitos G.'},
    {key:25, url: '/edades',       caption: 'Rangos Edad'},
    //{key:27, url: '/carnets',      caption: 'Carnets'},
    //{key:30, url: '/prestaciones', caption: 'Prestaciones'},
    {key:35, url: '/estados',      caption: 'Estados'},
    {key:34, url: '/plataformas',  caption: 'Plataformas'},
]

export default MenuItems;
